- name: Allocate CHAP User in the Hitachi Block Storage.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vsp.yml
  tasks:
  - name: Add CHAP user
    hitachi_block_addChap:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      port_id: '{{item.port_id}}'
      host_group_number: '{{item.host_group_number}}' # iSCSI Target ID
      chap_user_name: '{{item.chap_user_name}}'
      way_of_chap_user: '{{item.way_of_chap_user}}'
      chap_password: '{{item.chap_password}}'
    with_items:
      - '{{chap_settings}}'
    register: chap_result

  - name: Print add CHAP result
    debug:
      msg: '{{chap_result}}'
      
