- name: Allocate volume from Hitachi Block Storage .
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vsp.yml
  tasks:
  - name: Add Lun to iSCSI Target
    hitachi_block_addlun:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      port_id: '{{item.port_id}}'
      host_group_number: '{{item.host_group_number}}' # iSCSI Target ID
      ldev_id: '{{ldev_id}}'
      iscsi_name: '{{item.iscsi_name}}'             # iSCSI Initiator
    with_items:
      - '{{port_settings}}'
    register: lun_result

  - name: Print Lun information
    debug:
      msg: '{{lun_result}}'