- name: The following request sets the nickname for an iSCSI name registered for the iSCSI target
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vsp.yml
  tasks:
  - name: Change nickname for an iSCSI name registered for the iSCSI target
    hitachi_block_changeNickName:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      port_id: '{{item.port_id}}'
      host_group_number: '{{item.host_group_number}}' # iSCSI Target ID
      iscsi_name: '{{item.iscsi_name}}'               # iSCSI Initiator
      nick_name: '{{item.iscsi_nick_name}}'
    with_items:
      '{{port_settings}}'
