- name: Allocate volume from Hitachi Block Storage with ThinImage.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vsp.yml
  tasks:
  - name: Create ThinImage pair with generations
    hitachi_block_createTI_with_gen:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      snapshot_group_name: '{{TI.snapshot_group_name}}'
      snapshot_pool_id: '{{TI.snapshot_pool_id}}'
      pvol_ldev_id: '{{TI.ldev_id}}'
      is_consistency_group: '{{TI.is_consistency_group}}'
      generations: '{{TI.generations}}'
    register: TI_pair_result

  - name: Print create TI pair result
    debug:
      msg: '{{TI_pair_result.outputs}}'
