- name: Create ThinImage pair
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vsp.yml
  tasks:
  - name: Create ThinImage pair
    hitachi_block_createTI:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      snapshot_group_name: '{{TI.snapshot_group_name}}'
      snapshot_pool_id: '{{TI.snapshot_pool_id}}'
      pvol_ldev_id: '{{TI.ldev_id}}'
      is_consistency_group: '{{TI.is_consistency_group}}'
      mu_number: '{{TI.mu_number}}'
    register: TI_pair_result

  - name: Print create TI pair result
    debug:
      msg: '{{TI_pair_result.outputs}}'