- name: Delete the iSCSI name from the iSCSI target on Hitachi Block Storage.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vsp.yml
  tasks:
  - name: Delete iSCSI name from iSCSI target
    hitachi_block_deleteHost:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      port_id: '{{item.port_id}}'
      host_group_number: '{{item.host_group_number}}' # iSCSI Target ID
      iscsi_name: '{{item.iscsi_name}}'               # iSCSI Initiator
    with_items:
      - '{{port_settings}}'
    register: iscsi_result

  - name: Print delete iSCSI name result
    debug:
      msg: '{{iscsi_result}}'
