- name: Split ShadowImage pair.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vsp.yml
  tasks:
  - name: Split ShadowImage pair
    hitachi_block_splitSI:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      copy_group_name: '{{SI.copy_group_name}}'
      copy_pair_name: '{{SI.copy_pair_name}}'
    register: SI_split_result

  - name: Print split SI pair result
    debug:
      msg: '{{SI_split_result.outputs}}'
