- name: Split ThinImage pair.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vsp.yml
  tasks:
  - name: Split ThinImage pair
    hitachi_block_splitTI:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      snapshot_group_name: '{{TI.snapshot_group_name}}'
      pvol_ldev_id: '{{TI.ldev_id}}'
      mu_number: '{{TI.mu_number}}'
    register: TI_split_result

  - name: Print split TI pair result
    debug:
      msg: '{{TI_split_result.outputs}}'
