- name: Add iSCSI name to compute node of Hitachi Virtual Storage Software Block.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vssb.yml
  tasks:
  - name: Add iSCSI name to compute node
    add_hbas:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      server_nickname: '{{server_nickname}}' # Compute Node Name
      iscsi_name: '{{item.iscsi_name}}'      # iSCSI Initiator
    with_items:
      - '{{port_settings}}'
    register: result_add_iscsiname

  - name: Print create compute node result
    debug:
      msg: '{{result_add_iscsiname}}'
