- name: Add Compute Node to Hitachi Virtual Storage Software Block.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vssb.yml
  tasks:
  - name: Add path to compute node and compute port
    add_paths:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      server_nickname: '{{server_nickname}}'          # Compute Node Name
      iscsi_name: '{{item.iscsi_name}}'               # iSCSI Initiator
      target_port_name: '{{item.target_port_name}}'
    with_items:
      - '{{port_settings}}'
    register: result_add_paths

  - name: Print add path to compute node and compute port result
    debug:
      msg: '{{result_add_paths}}'
