- name: Create a volume on Hitachi Virtual Storage Software Block.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vssb.yml
  tasks:
  - name: Create volume
    create_volume:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      pool_name: '{{pool_name}}'
      capacity_mb: '{{volumes_capacity_mb}}'
      number: '{{volume_number}}'
      base_name: '{{volume_basename}}'
    register: result_create_volume

  - name: Print create volume result
    debug:
      msg: '{{result_create_volume}}'
    