- name: Delete Compute Node from Hitachi Virtual Storage Software Block.
  hosts: localhost
  connection: local
  vars_files:
    ../../vars/param_vssb.yml
  tasks:
  - name: Delete Compute Node
    delete_computenode:
      management_address: '{{management_address}}'
      management_port: '{{management_port}}'
      user: '{{storage_user}}'
      password: '{{storage_pass}}'
      server_nickname: '{{server_nickname}}'     # Compute Node Name
    register: result_delete_computenode

  - name: Print delete compute node result
    debug:
      msg: '{{result_delete_computenode}}'
